config/routes.rb
Rails.application.routes.draw do
  resources :password_resets
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'users/new'
  get 'users/create'
  root 'top#index'
  get 'top/about'
  get 'top/home'
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/create'
  get 'events/edit'
  get 'events/update'
  get 'events/destroy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  #skip_before_action :require_login

  def create
    @user = User.find_by_email(params[:email])
    @user&.deliver_reset_password_instructions!
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    return not_authenticated if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password(params[:user][:password])
      redirect_to login_path, success: "パスワードを変更できました"
    else
      flash.now[:danger] = "パスワード変更出来ませんでした"
      render :edit
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index; end

  def about; end

  def home; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to top_home_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'Top_logo.png' %>
    <% end %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            使い方
          </a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to '掲示板一覧', '#', class: 'dropdown-item' %>
            <%= link_to '掲示板作成', '#', class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to 'ブックマーク一覧', '#', class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="header-profile">
            <%= image_tag 'Top_logo.png', size: '40x40', class: 'rounded-circle mr15'%>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item">らんてっく たろう</div>
            <div class="dropdown-divider"></div>
            <%= link_to 'プロフィール', '#', class: 'dropdown-item' %>

            <%= link_to 'ログアウト', '#', class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>
<p>プロフィール</p>
<p>通知</p>
<p>イベント</p>
<p>ガレージ</p>
<p>ほしいもの</p>
<p>情報</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NimoTan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<% content_for(:title ,'パスワードリセット申請')%>
<div class="container">
    <div class="row">
        <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <h1>パスワードリセット申請</h1>
            <%= form_with url:password_resets_path,method: :post,local: true do |f|%>
                <div class="form-group">
                    <%=f.label :email, User.human_attribute_name(:email)%>
                    <%=f.text_field :email,class: "form-control"%>
                </div>
                <%=f.submit "送信",class:"btn btn-primary"%>
            <%end%>
        </div>
    </div>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/shared/_header.html.erb
<header class="navbar bg-secondary bg-dark shadow">
  <%= link_to image_tag 'header_logo.png', width: '150px', class: 'navbar-brand ms-3' %>
  </button>
  <div class="justify-content-end me-3">
    <%= link_to "ログイン", login_path, class: 'btn btn-light shadow' %>
    <%= link_to "アカウント作成", users_new_path, class: 'btn btn-outline-light shadow' %>
  </div>
</header>

app/views/top/about.html.erb
<header>
</header>

<body>
  <div class="top_rogo">
    <%= image_tag 'Top_logo.png', class: 'shadow_test', width: '30%' %>
  </div>
  <div>
    このアプリは、グループでのお出かけ時に、
    荷物を最小限にすることを目的にしたアプリです。
  </div>
  <div class="col">
		<button class="col btn btn-dark-moon btn-rounded shadow_test">開始</button>
	</div>
</body>

app/views/top/home.html.erb
<div class="container">
  <h1>nimo-tan</h1>
  <%= link_to "使い方", top_about_path, class: 'btn btn-outline-secondary btn-block' %>

  <!-- item card -->
    <div class="col-xl-3 col-sm-6 mb-5 centering_parent padding">
      <div class="bg-white rounded shadow-sm py-5 px-4">
        <%= image_tag 'user-solid.svg', width: '100px', height: '100px', class: "img-fluid rounded-circle mb-3 img-thumbnail shadow-sm" %>
        <h5 class="mb-0">プロフィール</h5>
      </div>
    </div>
  <!-- End -->

  <!-- item card -->
    <div class="col-xl-3 col-sm-6 mb-5 centering_parent padding">
      <div class="bg-white rounded shadow-sm py-5 px-4">
        <%= image_tag 'user-solid.svg', width: '100px', height: '100px', class: "img-fluid rounded-circle mb-3 img-thumbnail shadow-sm" %>
        <h5 class="mb-0">通知</h5>
      </div>
    </div>
  <!-- End -->

  <!-- item card -->
    <div class="col-xl-3 col-sm-6 mb-5 centering_parent padding">
      <div class="bg-white rounded shadow-sm py-5 px-4">
        <%= image_tag 'user-solid.svg', width: '100px', height: '100px', class: "img-fluid rounded-circle mb-3 img-thumbnail shadow-sm" %>
        <h5 class="mb-0">イベント</h5>
      </div>
    </div>
  <!-- End -->

  <!-- item card -->
    <div class="col-xl-3 col-sm-6 mb-5 centering_parent padding">
      <div class="bg-white rounded shadow-sm py-5 px-4">
        <%= image_tag 'user-solid.svg', width: '100px', height: '100px', class: "img-fluid rounded-circle mb-3 img-thumbnail shadow-sm" %>
        <h5 class="mb-0">ログアウト</h5>
      </div>
    </div>
  <!-- End -->
</div>

app/views/top/index.html.erb
<div class="top_header">
   <%= image_tag 'Top_logo.png', width: '250px' %>
</div>
<%= link_to "開始", "/login" %>
<%= link_to "使い方を見る", "" %>

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
    </div>
  <% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>Login</h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit 'Login', class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to 'Signup', new_user_path %>
      </div>
      <div class="actions">
        <h1>Forgot Password?</h1>
        <%= render 'forgot_password_form' %>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    This is some text within a card body.
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>New User</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: 'form-control' %>
        </div>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="form-group">
        <%= f.label :role %>
        <%= f.text_field :role, class: 'form-control' %>
        </div>        
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'Login', login_path %>
      </div>
    </div>
  </div>
</div>